import 'package:flutter/widgets.dart';

class SushiLocalizations {
  final Locale locale;
  SushiLocalizations(this.locale);

  static const LocalizationsDelegate<SushiLocalizations> delegate =
      _SushiLocalizationsDelegate();

  static SushiLocalizations of(BuildContext context) {
    return Localizations.of<SushiLocalizations>(context, SushiLocalizations)!;
  }

  static const _strings = {
    'en': {
      'app_name': 'Sushi-XL',
      'onboarding_title': 'Welcome',
      'onboarding_subtitle': 'Sushi‑XL delivery in one tap',
      'select_language': 'Select language',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'continue': 'Continue',
      'phone': 'Phone number',
      'full_name': 'Full name',
      'home': 'Home',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'place_order': 'Place order',
      'order_history': 'Order history',
      'profile': 'Profile',
      'working_hours': 'Working hours',
      'delivery': 'Delivery',
      'pickup': 'Pickup',
      'payment_cash': 'Cash',
      'payment_card': 'Card on delivery',
      'payment_online': 'Online (coming soon)',
      'cart_empty': 'Cart is empty',
      'total': 'Total',
      'modifiers': 'Modifiers',
      'address': 'Address',
      'delivery_location': 'Delivery location',
      'save_location': 'Save location',
      'location_saved': 'Location saved',
      'location_enter_address': 'Please enter address',
      'search_address': 'Search address',
      'address_not_found': 'Address not found',
      'use_current_location': 'Use current location',
      'location_service_disabled': 'Location services are disabled',
      'location_permission_denied': 'Location permission denied',
      'location_permission_denied_forever':
          'Location permission permanently denied. Enable it in Settings.',
      'location_not_set': 'Address not set',
      'add_address': 'Add address',
      'payment_method': 'Payment method',
      'payment_subtitle_cash': 'Pay when you receive',
      'payment_subtitle_card': 'Terminal available',
      'payment_subtitle_coming_soon': 'Coming soon',
      'order_notes': 'Order notes',
      'add_note': 'Add a note',
      'delivery_details': 'Delivery Details',
      'save_address': 'Save Address',
      'address_required': 'Address required',
      'address_saved': 'Address saved',
      'address_save_failed': 'Address save failed',
      'please_enter_address': 'Please enter address',
      'address_service_unavailable_continue':
          'Address service unavailable. Continuing with manual address.',
      'address_service_offline_manual':
          'Address service is offline. Enter address manually.',
      'free_delivery_progress': 'FREE DELIVERY PROGRESS',
      'free_delivery_away': '15 000 UZS away',
      'order_summary': 'Order Summary',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'tax': 'Tax',
      'login_required': 'Please login',
      'otp_code_prompt': 'Enter the verification code from SMS.',
      'otp_code_label': 'Verification code',
      'otp_code_required': 'Verification code is required.',
      'reorder': 'Reorder',
      'order': 'Order',
      'status': 'Status',
      'payment': 'Payment',
      'tracking': 'Tracking',
      'live_courier_not_available':
          'Live courier tracking is not available yet.',
      'status_pending': 'Pending',
      'status_accepted': 'Accepted',
      'status_sent': 'Sent',
      'status_preparing': 'Preparing',
      'status_on_the_way': 'On the way',
      'status_delivered': 'Delivered',
      'status_cancelled': 'Cancelled',
      'status_completed': 'Completed',
      'status_telegram_only': 'Sent to kitchen (Telegram)',
      'payment_pending': 'Pending',
      'payment_paid': 'Paid',
      'payment_unpaid': 'Unpaid',
      'tracking_backend_offline':
          'Server is offline. This order was submitted via Telegram and is awaiting confirmation.',
      'tracking_address_offline':
          'Address service is offline. Showing default map point.',
      'order_not_found': 'Order not found',
      'poster_id': 'Poster ID',
      'tap_to_continue': 'Tap to continue',
      'fetching_ingredients': 'FETCHING FRESH INGREDIENTS',
      'premium_delivery_experience': 'PREMIUM DELIVERY EXPERIENCE',
      'featured_selection': 'Featured Selection',
      'discount_products': 'Discount Products',
      'recommended_products': 'Recommended Products',
      'see_all': 'SEE ALL',
      'popular_now': 'Popular Now',
      'deliver_to': 'DELIVER TO',
      'deliver_to_your_address': 'Deliver to your address',
      'saved': 'Saved',
      'favorites': 'Favorites',
      'saved_empty_title': 'No saved items yet',
      'saved_empty_subtitle':
          'Save your favorite sushi\nto access them quickly',
      'orders': 'Orders',
      'mailings': 'Notifications',
      'no_mailings_yet': 'No notifications yet',
      'explore': 'Explore',
      'language': 'Language',
      'logout': 'Logout',
      'guest': 'Guest',
      'register': 'Register',
      'register_reminder': 'Complete registration for faster checkout',
      'premium_member': 'Premium Member',
      'current_order': 'Current Order',
      'active_tab': 'Active',
      'past_tab': 'Past',
      'no_active_orders': 'No active orders',
      'no_past_orders_yet': 'No past orders yet',
      'no_orders_subtitle':
          'Looks like you haven’t ordered yet. Let\'s fix that 🙂',
      'browse_menu': 'Browse menu',
      'reorder_favorites': 'Reorder favorites',
      'view_all': 'View All',
      'account_settings': 'ACCOUNT SETTINGS',
      'support_help': 'Support & Help',
      'support_short': 'Support',
      'profile_track_order': 'Track Order',
      'profile_track_order_subtitle': 'Track your delicious sushi in real time',
      'profile_my_orders': 'My Orders',
      'profile_my_orders_subtitle': 'Reorder your favorite rolls instantly',
      'support_contacts': 'Support & Contacts',
      'support_subtitle': "We're here to help you 24/7",
      'get_in_touch': 'GET IN TOUCH',
      'call_support': 'Call Support',
      'chat_with_us': 'Chat with us',
      'support_call_failed': 'Could not open the phone dialer.',
      'support_call_copied': 'Phone number copied to clipboard:',
      'support_chat_subtitle': 'Describe the issue and we will reply here.',
      'support_chat_intro':
          'The app will first try to answer using the support knowledge base. If the question is unclear, the chat is escalated to the admin.',
      'support_chat_unavailable':
          'Chat sync is unavailable right now. Please call support instead.',
      'support_chat_empty': 'Start the chat and describe your issue.',
      'support_message_hint': 'Write your issue here',
      'support_chat_send_failed': 'Could not send the message. Try again.',
      'support_app_badge': 'App assistant',
      'support_admin_badge': 'Admin',
      'you': 'You',
      'social_channels': 'SOCIAL CHANNELS',
      'common_questions': 'COMMON QUESTIONS',
      'faq_delivery_time_q': 'How long does delivery usually take?',
      'faq_delivery_time_a':
          'Most orders arrive within 30-45 minutes. During peak hours it can take up to 60 minutes.',
      'faq_cancel_order_q': 'Can I cancel my order?',
      'faq_cancel_order_a':
          'Orders can be cancelled within 5 minutes of placement.',
      'faq_payment_methods_q': 'What payment methods do you accept?',
      'faq_payment_methods_a':
          'We accept card on delivery and cash. Online payments are coming soon.',
      'app_version': 'App Version 2.4.0 (Build 1204)',
      'copyright_sushixl': '© 2024 Sushi-XL Gourmet Delivery',
      'privacy_policy': 'Privacy Policy',
      'admin_login_title': 'Admin Login',
      'admin_login_subtitle': 'Enter login and password to open admin panel',
      'admin_name': 'Login',
      'admin_password': 'Password',
      'admin_open_panel': 'Open Admin Panel',
      'admin_default_login': 'Default login',
      'admin_wrong_credentials': 'Wrong name or password',
      'proceed_checkout': 'Proceed to Checkout',
      'terms_notice': "By ordering, you agree to Sushi-XL's Terms",
      'order_success_title': 'Order Success',
      'order_success_thank_you': 'Thank you for your order!',
      'order_success_subtitle':
          'Our chefs are already preparing your fresh sushi. Get ready for a delicious meal!',
      'order_success_hero_title': 'Your sushi is on the way',
      'order_success_hero_subtitle':
          'Our chefs have started preparing your order.',
      'order_success_prepared_for_you': 'Freshly prepared\nfor you',
      'estimated_arrival': 'Estimated Arrival',
      'order_id': 'Order ID',
      'track_live_order': 'Track Live Order',
      'track_my_order': 'Track My Order',
      'return_home': 'Return Home',
      'back_to_menu': 'Back to Menu',
      'profile_edit_title': 'Edit profile',
      'save': 'Save',
      'cat_drinks': 'Drinks',
      'cat_rolls': 'Rolls',
      'cat_sushi': 'Sushi',
      'cat_salads': 'Salads',
      'cat_sets': 'Sets',
      'cat_sauces': 'Sauces',
      'cat_baked': 'Baked',
      'cat_mini_rolls': 'Mini rolls',
      'cat_cold_dishes': 'Cold dishes',
      'cat_fried_rolls': 'Fried rolls',
      'cat_kimbap': 'Kimbap',
      'cat_hot_dishes': 'Hot dishes',
      'cat_new_items': 'New items',
      'cat_bread': 'Bread',
      'cat_soups': 'Soups',
      'cat_desserts': 'Desserts',
      'not_found': 'Not found',
      'search_products_hint': 'Search sushi, rolls, drinks...',
      'no_results': 'No results',
      'items_available': 'items available',
      'menu': 'Menu',
      'filter': 'Filter',
      'price': 'Price',
      'popularity': 'Popularity',
      'spicy': 'Spicy',
      'add_to_cart': 'Add to Cart',
      'addons_extras': 'Add-ons & Extras',
      'product_not_found': 'Product not found',
      'generic_error': 'Error',
      'session_not_found_login_again': 'Session not found. Please login again.',
      'please_enter_full_name': 'Please enter full name.',
      'profile_saved_successfully': 'Profile saved successfully.',
      'save_failed': 'Save failed',
      'order_failed': 'Order failed',
      'order_sent_telegram_fallback':
          'Server is offline. Order sent to Telegram.',
      'order_created_telegram_failed':
          'Order created, but Telegram notify failed',
      'pieces_label': 'Pieces',
      'fresh_raw': 'Fresh Raw',
      'free': 'Free',
      'map_not_supported_platform': 'Map is not supported on this platform',
      'address_label_home_office': 'Label (Home/Office)',
      'latitude_optional': 'Latitude (optional)',
      'longitude_optional': 'Longitude (optional)',
    },
    'ru': {
      'app_name': 'Sushi-XL',
      'onboarding_title': 'Добро пожаловать',
      'onboarding_subtitle': 'Доставка Sushi‑XL в одно касание',
      'select_language': 'Выберите язык',
      'gender': 'Пол',
      'male': 'Мужской',
      'female': 'Женский',
      'other': 'Другое',
      'continue': 'Продолжить',
      'phone': 'Номер телефона',
      'full_name': 'Полное имя',
      'home': 'Главная',
      'cart': 'Корзина',
      'checkout': 'Оформление',
      'place_order': 'Оформить заказ',
      'order_history': 'История заказов',
      'profile': 'Профиль',
      'working_hours': 'Часы работы',
      'delivery': 'Доставка',
      'pickup': 'Самовывоз',
      'payment_cash': 'Наличными',
      'payment_card': 'Карта при доставке',
      'payment_online': 'Онлайн (Скоро)',
      'cart_empty': 'Корзина пуста',
      'total': 'Итого',
      'modifiers': 'Модификаторы',
      'address': 'Адрес',
      'delivery_location': 'Адрес доставки',
      'save_location': 'Сохранить локацию',
      'location_saved': 'Локация сохранена',
      'location_enter_address': 'Пожалуйста, введите адрес',
      'search_address': 'Найти адрес',
      'address_not_found': 'Адрес не найден',
      'use_current_location': 'Текущая локация',
      'location_service_disabled': 'Служба геолокации отключена',
      'location_permission_denied': 'Доступ к геолокации запрещен',
      'location_permission_denied_forever':
          'Доступ к геолокации навсегда запрещен. Включите его в настройках.',
      'location_not_set': 'Адрес не выбран',
      'add_address': 'Добавить адрес',
      'payment_method': 'Способ оплаты',
      'payment_subtitle_cash': 'Оплатите при получении',
      'payment_subtitle_card': 'Терминал доступен',
      'payment_subtitle_coming_soon': 'Скоро',
      'order_notes': 'Комментарий к заказу',
      'add_note': 'Добавьте комментарий',
      'delivery_details': 'Детали доставки',
      'save_address': 'Сохранить адрес',
      'address_required': 'Требуется адрес',
      'address_saved': 'Адрес сохранен',
      'address_save_failed': 'Не удалось сохранить адрес',
      'please_enter_address': 'Пожалуйста, введите адрес',
      'address_service_unavailable_continue':
          'Сервис адресов недоступен. Продолжаем с ручным адресом.',
      'address_service_offline_manual':
          'Сервис адресов недоступен. Введите адрес вручную.',
      'free_delivery_progress': 'ПРОГРЕСС БЕСПЛАТНОЙ ДОСТАВКИ',
      'free_delivery_away': 'Осталось 15 000 UZS',
      'order_summary': 'Сводка заказа',
      'subtotal': 'Промежуточный итог',
      'delivery_fee': 'Доставка',
      'tax': 'Налог',
      'login_required': 'Пожалуйста, войдите',
      'otp_code_prompt': 'Введите код подтверждения из SMS.',
      'otp_code_label': 'Код подтверждения',
      'otp_code_required': 'Требуется код подтверждения.',
      'reorder': 'Повторить',
      'order': 'Заказ',
      'status': 'Статус',
      'payment': 'Оплата',
      'tracking': 'Отслеживание',
      'live_courier_not_available':
          'Онлайн-отслеживание курьера пока недоступно.',
      'status_pending': 'Ожидает',
      'status_accepted': 'Принят',
      'status_sent': 'Отправлен',
      'status_preparing': 'Готовится',
      'status_on_the_way': 'В пути',
      'status_delivered': 'Доставлен',
      'status_cancelled': 'Отменён',
      'status_completed': 'Завершён',
      'status_telegram_only': 'Отправлен на кухню (Telegram)',
      'payment_pending': 'Ожидание',
      'payment_paid': 'Оплачено',
      'payment_unpaid': 'Не оплачено',
      'tracking_backend_offline':
          'Сервер недоступен. Этот заказ отправлен через Telegram и ожидает подтверждения.',
      'tracking_address_offline':
          'Сервис адресов недоступен. Показана точка по умолчанию.',
      'order_not_found': 'Заказ не найден',
      'poster_id': 'Poster ID',
      'tap_to_continue': 'Нажмите, чтобы продолжить',
      'fetching_ingredients': 'ГОТОВИМ СВЕЖИЕ ИНГРЕДИЕНТЫ',
      'premium_delivery_experience': 'ПРЕМИАЛЬНАЯ ДОСТАВКА',
      'featured_selection': 'Рекомендуем',
      'discount_products': 'Товары со скидкой',
      'recommended_products': 'Рекомендуемые товары',
      'see_all': 'СМОТРЕТЬ ВСЕ',
      'popular_now': 'Популярное',
      'deliver_to': 'ДОСТАВКА В',
      'deliver_to_your_address': 'Доставка на ваш адрес',
      'saved': 'Избранное',
      'favorites': 'Избранное',
      'saved_empty_title': 'Пока нет сохраненных блюд',
      'saved_empty_subtitle':
          'Сохраняйте любимые суши,\nчтобы быстро находить их',
      'orders': 'Заказы',
      'mailings': 'Уведомления',
      'no_mailings_yet': 'Пока нет уведомлений',
      'explore': 'Обзор',
      'language': 'Язык',
      'logout': 'Выйти',
      'guest': 'Гость',
      'register': 'Регистрация',
      'register_reminder': 'Завершите регистрацию для быстрого оформления',
      'premium_member': 'Премиум участник',
      'current_order': 'Текущий заказ',
      'active_tab': 'Активные',
      'past_tab': 'Прошлые',
      'no_active_orders': 'Нет активных заказов',
      'no_past_orders_yet': 'Прошлых заказов пока нет',
      'no_orders_subtitle':
          'Похоже, вы еще ничего не заказывали. Давайте это исправим 🙂',
      'browse_menu': 'Открыть меню',
      'reorder_favorites': 'Повторить избранное',
      'view_all': 'Смотреть все',
      'account_settings': 'НАСТРОЙКИ АККАУНТА',
      'support_help': 'Поддержка и помощь',
      'support_short': 'Поддержка',
      'profile_track_order': 'Отследить заказ',
      'profile_track_order_subtitle':
          'Следите за своим вкусным суши-заказом в реальном времени',
      'profile_my_orders': 'Мои заказы',
      'profile_my_orders_subtitle':
          'Быстро повторяйте любимые роллы в пару касаний',
      'support_contacts': 'Поддержка и контакты',
      'support_subtitle': 'Мы на связи 24/7',
      'get_in_touch': 'СВЯЗАТЬСЯ С НАМИ',
      'call_support': 'Позвонить в поддержку',
      'chat_with_us': 'Написать в чат',
      'support_call_failed': 'Не удалось открыть набор номера.',
      'support_call_copied': 'Номер скопирован в буфер обмена:',
      'support_chat_subtitle': 'Опишите проблему, и мы ответим здесь.',
      'support_chat_intro':
          'Сначала приложение попробует ответить по базе частых вопросов. Если вопрос окажется сложным, чат будет передан администратору.',
      'support_chat_unavailable':
          'Синхронизация чата сейчас недоступна. Пожалуйста, позвоните в поддержку.',
      'support_chat_empty': 'Начните чат и опишите свою проблему.',
      'support_message_hint': 'Напишите ваш вопрос',
      'support_chat_send_failed':
          'Не удалось отправить сообщение. Попробуйте еще раз.',
      'support_app_badge': 'Ассистент приложения',
      'support_admin_badge': 'Админ',
      'you': 'Вы',
      'social_channels': 'СОЦИАЛЬНЫЕ КАНАЛЫ',
      'common_questions': 'ЧАСТЫЕ ВОПРОСЫ',
      'faq_delivery_time_q': 'Сколько обычно занимает доставка?',
      'faq_delivery_time_a':
          'Большинство заказов приезжает за 30-45 минут. В часы пик до 60 минут.',
      'faq_cancel_order_q': 'Можно ли отменить заказ?',
      'faq_cancel_order_a':
          'Заказ можно отменить в течение 5 минут после оформления.',
      'faq_payment_methods_q': 'Какие способы оплаты вы принимаете?',
      'faq_payment_methods_a':
          'Мы принимаем наличные и карту при доставке. Онлайн-оплата скоро появится.',
      'app_version': 'Версия приложения 2.4.0 (Сборка 1204)',
      'copyright_sushixl': '© 2024 Sushi-XL Gourmet Delivery',
      'privacy_policy': 'Политика конфиденциальности',
      'admin_login_title': 'Вход администратора',
      'admin_login_subtitle': 'Введите логин и пароль для входа в админ-панель',
      'admin_name': 'Логин',
      'admin_password': 'Пароль',
      'admin_open_panel': 'Открыть админ-панель',
      'admin_default_login': 'Логин по умолчанию',
      'admin_wrong_credentials': 'Неверное имя или пароль',
      'proceed_checkout': 'Перейти к оплате',
      'terms_notice': 'Оформляя заказ, вы соглашаетесь с условиями Sushi-XL',
      'order_success_title': 'Заказ оформлен',
      'order_success_thank_you': 'Спасибо за ваш заказ!',
      'order_success_subtitle':
          'Наши повара уже готовят ваш свежий суши. Скоро будет вкусно!',
      'order_success_hero_title': 'Ваш суши уже в пути',
      'order_success_hero_subtitle':
          'Наши повара уже начали готовить ваш заказ.',
      'order_success_prepared_for_you': 'Свежо приготовлено\nдля вас',
      'estimated_arrival': 'Ожидаемое время',
      'order_id': 'Номер заказа',
      'track_live_order': 'Отслеживать заказ',
      'track_my_order': 'Отследить заказ',
      'return_home': 'На главную',
      'back_to_menu': 'Назад в меню',
      'profile_edit_title': 'Редактировать профиль',
      'save': 'Сохранить',
      'cat_drinks': 'Напитки',
      'cat_rolls': 'Роллы',
      'cat_sushi': 'Суши',
      'cat_salads': 'Салаты',
      'cat_sets': 'Сеты',
      'cat_sauces': 'Соусы',
      'cat_baked': 'Запеченные',
      'cat_mini_rolls': 'Мини роллы',
      'cat_cold_dishes': 'Холодные блюда',
      'cat_fried_rolls': 'Жаренные роллы',
      'cat_kimbap': 'Кимпаб',
      'cat_hot_dishes': 'Горячка',
      'cat_new_items': 'Новинки',
      'cat_bread': 'Хлеб',
      'cat_soups': 'Супы',
      'cat_desserts': 'Десерты',
      'not_found': 'Не найдено',
      'search_products_hint': 'Поиск суши, роллов, напитков...',
      'no_results': 'Ничего не найдено',
      'items_available': 'товаров доступно',
      'menu': 'Меню',
      'filter': 'Фильтр',
      'price': 'Цена',
      'popularity': 'Популярность',
      'spicy': 'Острое',
      'add_to_cart': 'Добавить в корзину',
      'addons_extras': 'Добавки и опции',
      'product_not_found': 'Товар не найден',
      'generic_error': 'Ошибка',
      'session_not_found_login_again': 'Сессия не найдена. Войдите снова.',
      'please_enter_full_name': 'Пожалуйста, введите полное имя.',
      'profile_saved_successfully': 'Профиль успешно сохранен.',
      'save_failed': 'Сохранение не удалось',
      'order_failed': 'Ошибка заказа',
      'order_sent_telegram_fallback':
          'Сервер недоступен. Заказ отправлен в Telegram.',
      'order_created_telegram_failed':
          'Заказ создан, но уведомление в Telegram не отправлено',
      'pieces_label': 'шт',
      'fresh_raw': 'Свежий продукт',
      'free': 'Бесплатно',
      'map_not_supported_platform': 'Карта не поддерживается на этой платформе',
      'address_label_home_office': 'Метка (Дом/Офис)',
      'latitude_optional': 'Широта (необязательно)',
      'longitude_optional': 'Долгота (необязательно)',
    },
    'uz': {
      'app_name': 'Sushi-XL',
      'onboarding_title': 'Xush kelibsiz',
      'onboarding_subtitle': 'Sushi‑XL yetkazib berish bir bosishda',
      'select_language': 'Tilni tanlang',
      'gender': 'Jins',
      'male': 'Erkak',
      'female': 'Ayol',
      'other': 'Boshqa',
      'continue': 'Davom etish',
      'phone': 'Telefon raqam',
      'full_name': 'To‘liq ism',
      'home': 'Bosh sahifa',
      'cart': 'Savat',
      'checkout': 'Buyurtma berish',
      'place_order': 'Buyurtma berish',
      'order_history': 'Buyurtmalar tarixi',
      'profile': 'Profil',
      'working_hours': 'Ish vaqti',
      'delivery': 'Yetkazib berish',
      'pickup': 'Olib ketish',
      'payment_cash': 'Naqd',
      'payment_card': 'Yetkazishda karta',
      'payment_online': 'Onlayn (Tez kunda)',
      'cart_empty': 'Savat bo‘sh',
      'total': 'Jami',
      'modifiers': 'Modifikatorlar',
      'address': 'Manzil',
      'delivery_location': 'Yetkazib berish manzili',
      'save_location': 'Lokatsiyani saqlash',
      'location_saved': 'Lokatsiya saqlandi',
      'location_enter_address': 'Iltimos, manzilni kiriting',
      'search_address': 'Manzilni qidirish',
      'address_not_found': 'Manzil topilmadi',
      'use_current_location': 'Joriy joylashuv',
      'location_service_disabled': 'Lokatsiya xizmati o‘chirilgan',
      'location_permission_denied': 'Lokatsiyaga ruxsat berilmagan',
      'location_permission_denied_forever':
          'Lokatsiyaga ruxsat doimiy rad etilgan. Sozlamalarda yoqing.',
      'location_not_set': 'Manzil tanlanmagan',
      'add_address': 'Manzil qo‘shish',
      'payment_method': 'To‘lov usuli',
      'payment_subtitle_cash': 'Qabul qilganda to‘lang',
      'payment_subtitle_card': 'Terminal mavjud',
      'payment_subtitle_coming_soon': 'Tez kunda',
      'order_notes': 'Buyurtma izohi',
      'add_note': 'Izoh qo‘shing',
      'delivery_details': 'Yetkazib berish tafsilotlari',
      'save_address': 'Manzilni saqlash',
      'address_required': 'Manzil kerak',
      'address_saved': 'Manzil saqlandi',
      'address_save_failed': 'Manzilni saqlashda xatolik',
      'please_enter_address': 'Iltimos, manzilni kiriting',
      'address_service_unavailable_continue':
          'Manzil xizmati ishlamayapti. Qo‘lda manzil bilan davom etiladi.',
      'address_service_offline_manual':
          'Manzil xizmati ishlamayapti. Manzilni qo‘lda kiriting.',
      'free_delivery_progress': 'BEPUL YETKAZISH JARAYONI',
      'free_delivery_away': 'Yana 15 000 UZS qoldi',
      'order_summary': 'Buyurtma xulosasi',
      'subtotal': 'Oraliq jami',
      'delivery_fee': 'Yetkazish narxi',
      'tax': 'Soliq',
      'login_required': 'Iltimos, tizimga kiring',
      'otp_code_prompt': 'SMS orqali yuborilgan tasdiqlash kodini kiriting.',
      'otp_code_label': 'Tasdiqlash kodi',
      'otp_code_required': 'Tasdiqlash kodi kerak.',
      'reorder': 'Qayta buyurtma',
      'order': 'Buyurtma',
      'status': 'Holat',
      'payment': 'To‘lov',
      'tracking': 'Kuzatish',
      'live_courier_not_available':
          'Jonli kuryer kuzatuvi hozircha mavjud emas.',
      'status_pending': 'Kutilmoqda',
      'status_accepted': 'Qabul qilindi',
      'status_sent': 'Yuborilgan',
      'status_preparing': 'Tayyorlanmoqda',
      'status_on_the_way': 'Yo‘lda',
      'status_delivered': 'Yetkazildi',
      'status_cancelled': 'Bekor qilindi',
      'status_completed': 'Yakunlandi',
      'status_telegram_only': 'Oshxonaga yuborildi (Telegram)',
      'payment_pending': 'Kutilmoqda',
      'payment_paid': 'To‘langan',
      'payment_unpaid': 'To‘lanmagan',
      'tracking_backend_offline':
          'Server ishlamayapti. Bu buyurtma Telegram orqali yuborildi va tasdiq kutilmoqda.',
      'tracking_address_offline':
          'Manzil xizmati ishlamayapti. Xaritada standart nuqta ko‘rsatildi.',
      'order_not_found': 'Buyurtma topilmadi',
      'poster_id': 'Poster ID',
      'tap_to_continue': 'Davom etish uchun bosing',
      'fetching_ingredients': 'YANGI MAHSULOTLAR TAYYORLANMOQDA',
      'premium_delivery_experience': 'PREMIUM YETKAZIB BERISH',
      'featured_selection': 'Tavsiya etilgan',
      'discount_products': 'Chegirmadagi mahsulotlar',
      'recommended_products': 'Tavsiya etilgan mahsulotlar',
      'see_all': 'BARCHASI',
      'popular_now': 'Hozir ommabop',
      'deliver_to': 'YETKAZISH',
      'deliver_to_your_address': 'Manzilingizga yetkazish',
      'saved': 'Saqlangan',
      'favorites': 'Sevimlilar',
      'saved_empty_title': 'Hali saqlangan mahsulotlar yo‘q',
      'saved_empty_subtitle':
          'Sevimli sushilaringizni saqlang,\nularni tez topasiz',
      'orders': 'Buyurtmalar',
      'mailings': 'Bildirishnomalar',
      'no_mailings_yet': 'Hozircha bildirishnomalar yo‘q',
      'explore': 'Ko‘rib chiqish',
      'language': 'Til',
      'logout': 'Chiqish',
      'guest': 'Mehmon',
      'register': 'Ro‘yxatdan o‘tish',
      'register_reminder':
          'Tezroq buyurtma uchun ro‘yxatdan o‘tishni yakunlang',
      'premium_member': 'Premium aʼzo',
      'current_order': 'Hozirgi buyurtma',
      'active_tab': 'Faol',
      'past_tab': 'O‘tgan',
      'no_active_orders': 'Faol buyurtmalar yo‘q',
      'no_past_orders_yet': 'Hozircha avvalgi buyurtmalar yo‘q',
      'no_orders_subtitle':
          'Siz hali buyurtma bermaganga o‘xshaysiz. Keling, buni to‘g‘rilaymiz 🙂',
      'browse_menu': 'Menyuni ko‘rish',
      'reorder_favorites': 'Sevimlilarni ochish',
      'view_all': 'Barchasini ko‘rish',
      'account_settings': 'AKKAUNT SOZLAMALARI',
      'support_help': 'Yordam va qo‘llab-quvvatlash',
      'support_short': 'Yordam',
      'profile_track_order': 'Buyurtmani kuzatish',
      'profile_track_order_subtitle':
          'Mazali sushi buyurtmangizni real vaqtda kuzating',
      'profile_my_orders': 'Mening buyurtmalarim',
      'profile_my_orders_subtitle':
          'Sevimli rollaringizni tezda qayta buyurtma qiling',
      'support_contacts': 'Yordam va aloqa',
      'support_subtitle': 'Biz sizga 24/7 yordam beramiz',
      'get_in_touch': 'BOG‘LANISH',
      'call_support': 'Qo‘llab-quvvatlashga qo‘ng‘iroq',
      'chat_with_us': 'Chat orqali yozing',
      'support_call_failed': 'Telefon terish oynasini ochib bo‘lmadi.',
      'support_call_copied': 'Raqam vaqtinchalik xotiraga nusxalandi:',
      'support_chat_subtitle': 'Muammoni yozing, shu yerda javob beramiz.',
      'support_chat_intro':
          'Ilova avval savolingizga yordam bazasi orqali javob berishga harakat qiladi. Savol murakkab bo‘lsa, chat adminlarga yuboriladi.',
      'support_chat_unavailable':
          'Chat sinxronizatsiyasi hozir ishlamayapti. Iltimos, qo‘llab-quvvatlashga qo‘ng‘iroq qiling.',
      'support_chat_empty': 'Chatni boshlang va muammoingizni yozing.',
      'support_message_hint': 'Muammoingizni shu yerga yozing',
      'support_chat_send_failed': 'Xabar yuborilmadi. Qayta urinib ko‘ring.',
      'support_app_badge': 'Ilova yordamchisi',
      'support_admin_badge': 'Admin',
      'you': 'Siz',
      'social_channels': 'IJTIMOIY TARMOQLAR',
      'common_questions': 'KO‘P SO‘RALADIGAN SAVOLLAR',
      'faq_delivery_time_q': 'Yetkazib berish odatda qancha vaqt oladi?',
      'faq_delivery_time_a':
          'Ko‘p buyurtmalar 30-45 daqiqada yetib boradi. Tig‘iz paytda 60 daqiqagacha cho‘zilishi mumkin.',
      'faq_cancel_order_q': 'Buyurtmani bekor qilsam bo‘ladimi?',
      'faq_cancel_order_a':
          'Buyurtma berilgandan keyin 5 daqiqa ichida bekor qilish mumkin.',
      'faq_payment_methods_q': 'Qaysi to‘lov usullari qabul qilinadi?',
      'faq_payment_methods_a':
          'Naqd va yetkazib berishda karta qabul qilinadi. Onlayn to‘lov tez kunda.',
      'app_version': 'Ilova versiyasi 2.4.0 (Build 1204)',
      'copyright_sushixl': '© 2024 Sushi-XL Gourmet Delivery',
      'privacy_policy': 'Maxfiylik siyosati',
      'admin_login_title': 'Admin kirish',
      'admin_login_subtitle':
          'Admin panelga kirish uchun login va parolni kiriting',
      'admin_name': 'Login',
      'admin_password': 'Parol',
      'admin_open_panel': 'Admin panelni ochish',
      'admin_default_login': 'Standart login',
      'admin_wrong_credentials': 'Ism yoki parol noto‘g‘ri',
      'proceed_checkout': 'To‘lovga o‘tish',
      'terms_notice':
          'Buyurtma berish orqali Sushi-XL shartlariga rozilik bildirasiz',
      'order_success_title': 'Buyurtma muvaffaqiyatli',
      'order_success_thank_you': 'Buyurtmangiz uchun rahmat!',
      'order_success_subtitle':
          'Oshpazlarimiz sizning yangi sushi buyurtmangizni tayyorlamoqda. Yoqimli ishtaha!',
      'order_success_hero_title': 'Sizning sushi yo‘lda',
      'order_success_hero_subtitle':
          'Oshpazlarimiz buyurtmangizni tayyorlashni boshladi.',
      'order_success_prepared_for_you': 'Yangi tayyorlandi\nsiz uchun',
      'estimated_arrival': 'Taxminiy yetib kelish vaqti',
      'order_id': 'Buyurtma ID',
      'track_live_order': 'Jonli kuzatish',
      'track_my_order': 'Buyurtmani kuzatish',
      'return_home': 'Bosh sahifaga qaytish',
      'back_to_menu': 'Menyuga qaytish',
      'profile_edit_title': 'Profilni tahrirlash',
      'save': 'Saqlash',
      'cat_drinks': 'Ichimliklar',
      'cat_rolls': 'Rolllar',
      'cat_sushi': 'Sushi',
      'cat_salads': 'Salatlar',
      'cat_sets': 'Setlar',
      'cat_sauces': 'Souslar',
      'cat_baked': 'Pishirilganlar',
      'cat_mini_rolls': 'Mini rolllar',
      'cat_cold_dishes': 'Sovuq taomlar',
      'cat_fried_rolls': 'Qovurilgan rolllar',
      'cat_kimbap': 'Kimbap',
      'cat_hot_dishes': 'Issiq taomlar',
      'cat_new_items': 'Yangi mahsulotlar',
      'cat_bread': 'Non',
      'cat_soups': 'Sho\'rvalar',
      'cat_desserts': 'Desertlar',
      'not_found': 'Topilmadi',
      'search_products_hint': 'Sushi, roll, ichimliklarni qidiring...',
      'no_results': 'Natija topilmadi',
      'items_available': 'ta mahsulot mavjud',
      'menu': 'Menyu',
      'filter': 'Filtr',
      'price': 'Narx',
      'popularity': 'Ommabop',
      'spicy': 'Achchiq',
      'add_to_cart': 'Savatga qo‘shish',
      'addons_extras': 'Qo‘shimchalar',
      'product_not_found': 'Mahsulot topilmadi',
      'generic_error': 'Xatolik',
      'session_not_found_login_again':
          'Sessiya topilmadi. Qayta tizimga kiring.',
      'please_enter_full_name': 'Iltimos, to‘liq ismni kiriting.',
      'profile_saved_successfully': 'Profil muvaffaqiyatli saqlandi.',
      'save_failed': 'Saqlash muvaffaqiyatsiz',
      'order_failed': 'Buyurtma xatosi',
      'order_sent_telegram_fallback':
          'Server ishlamayapti. Buyurtma Telegramga yuborildi.',
      'order_created_telegram_failed':
          'Buyurtma yaratildi, lekin Telegram xabari yuborilmadi',
      'pieces_label': 'dona',
      'fresh_raw': 'Yangi mahsulot',
      'free': 'Bepul',
      'map_not_supported_platform':
          'Bu platformada xarita qo‘llab-quvvatlanmaydi',
      'address_label_home_office': 'Yorliq (Uy/Ofis)',
      'latitude_optional': 'Kenglik (ixtiyoriy)',
      'longitude_optional': 'Uzunlik (ixtiyoriy)',
    },
  };

  String t(String key) {
    return _strings[locale.languageCode]?[key] ?? _strings['en']![key] ?? key;
  }
}

class _SushiLocalizationsDelegate
    extends LocalizationsDelegate<SushiLocalizations> {
  const _SushiLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['uz', 'ru', 'en'].contains(locale.languageCode);

  @override
  Future<SushiLocalizations> load(Locale locale) async {
    return SushiLocalizations(locale);
  }

  @override
  bool shouldReload(_SushiLocalizationsDelegate old) => false;
}
